### PR TITLE
created windows service for logrotate that runs periodically.

### PR DESCRIPTION
**Pull request by m-abubakar**
fixed copytruncate option when log file is in use.
added notifempty
reformatted code a little.

### CODE REVIEW

**Comment by 61131** [comment]
@plecos - Is there still interest in this functionality? While this pull request is something of a mess, if there is interest, I could go through and produce a smaller, cleaner version of this pull request.

**Comment by ghost** [comment]
I would definitely be interested @61131 ...

**Comment by 61131** [comment]
@yannouchou - For my immediate purposes, I was able to use the schtasks utility (https://msdn.microsoft.com/en-us/library/windows/desktop/bb736357(v=vs.85).aspx) to configure Logrotatewin to run periodically. This configuration can additionally be enacted from the Windows Task Scheduler.

**Comment by m-abubakar** [comment]
Sorry for the mess, I will submit a cleaner version in a few days.

**Pull request closed without merging**
